sudo: false
dist: trusty
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
language: cpp
script: make -j4 -k
